version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
  commit-message:
    prefix: deps(go)
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "02:00"
    timezone: Etc/UTC
  open-pull-requests-limit: 10
  commit-message:
    prefix: deps(actions)
