linters-settings:
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
  gocyclo:
    min-complexity: 10
  gocritic:
    disabled-checks:
      - commentFormatting
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 4
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - gocognit
    - goconst
    - gocritic
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - gocognit
        - govet
        - dupl
