name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go: [ '1.21', '1.22' ]

    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Run tests
      run: |
        go test -v -coverprofile="cover-profile.out" -short -race ./...
