name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Run tests
      run: |
        go test -v -coverprofile="cover-profile.out" -short -race ./...
