name: Conventional Commits

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: webiny/action-conventional-commits@faccb24fc2550dd15c0390d944379d2d8ed9690e # v1.3.1
        with:
          allowed-commit-types: feat,fix,docs,deps,chore,build,ci
