name: 'Stale issue handler'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        # See https://github.com/actions/stale#all-options
        with:
          days-before-stale: 60
          days-before-close: 14
          stale-issue-message: |
            This issue is stale because it has been open for 60 days with no activity. Remove `stale` label or comment or this will be automatically closed in a few days.
          stale-pr-message: |
            This pull request is stale because it has been open for 60 days with no activity. Remove `stale` label or comment or this will be automatically closed in a few days.
