name: Trivy Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Install Trivy
      uses: aquasecurity/setup-trivy@9ea583eb67910444b1f64abf338bd2e105a0a93d # v0.2.3
      with:
        version: v0.58.1
        cache: true
    - name: Download Trivy DB
      run: |
        trivy fs --no-progress --download-db-only --db-repository public.ecr.aws/aquasecurity/trivy-db
    - name: Run Trivy vulnerability scanner (table output)
      # Use the trivy binary rather than the aquasecurity/trivy-action action
      # to avoid a few bugs
      run: |
        trivy fs \
          --scanners vuln \
          --format table \
          --exit-code 1 \
          --ignore-unfixed \
          --pkg-types os,library \
          --severity CRITICAL,HIGH \
          --ignorefile .trivyignore \
          --skip-db-update \
          .
    - name: Run Trivy vulnerability scanner
      # Use the trivy binary rather than the aquasecurity/trivy-action action
      # to avoid a few bugs
      run: |
        trivy fs \
          --scanners vuln \
          --format sarif \
          --output trivy-results.sarif \
          --ignore-unfixed \
          --pkg-types os,library \
          --skip-db-update \
          .
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@181d5eefc20863364f96762470ba6f862bdef56b # v3.29.2
      with:
        sarif_file: 'trivy-results.sarif'
      if: always() && github.repository == 'grafana/certmagic-gcs'
